require_remote "./lib/scene/base.rb"
require_remote "./lib/scene/title.rb"
require_remote "./lib/scene/talk.rb"
require_remote "./lib/scene/battle.rb"
require_remote "./lib/scene/gameover.rb"
require_remote "./lib/scene/gameclear.rb"
